### ISSUE TITLE
file system mounting 

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#12]

**Comment by duxan** [comment]
Hi Tengfei, do you mean mounting project files here?

**Comment by tengfei** [comment]
yes when we release the vsfs client. I used to have some code for the old java version https://github.com/sbg/sevenbridges-r/blob/master/R/FS-class.R  this may require user install the client first. I am more thinking the official image here, so when I launch the Rstudio from image, I got bunny/docker/vsfs all preloaded, and they can directly mount projects from within R

**Comment by tengfei** [comment]
not the scope of this package anymore
