### ISSUE TITLE
Error: could not find function "Auth"

### ISSUE THREAD

**Issue by DurgaAdd** [sbg/sevenbridges-r#15]
Hi TengFei,
I followed your tutorials and tried to connect to SB-CGC from RStudio, but got the following error:

> a <- Auth(token = "(my token here)", url = "https://cgc-api.sbgenomics.com/v2/")
> Error: could not find function "Auth"

tx,
Durga

**Comment by tengfei** [comment]
Hi Durga 

I think you probably forget to run this?

library(sevenbridges)

If you did, could you please attach your

sessionInfo() here as well

Thanks

**Comment by DurgaAdd** [comment]
Yes, thank you!
I was blindly following the steps from your hackathon link (http://www.tengfei.name/sevenbridges/cgc-hackathon-2016-04/bioc-workflow.html). The bioc-workflow.R has this step included.
thanks.

**Comment by tengfei** [comment]
Thank you, any feedback are welcomed : ) Please feel free to file issue or feature request here, I will try to add/fix it asap.
