### ISSUE TITLE
lift single R markdown into everything 

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#16]
from R markdown with headers into
1. command line script 
2. Dockerfile
3. cwl json file 
4. combined with API client, when token provided, push to repos you specified. should I support any public repos config?

**Comment by seandavi** [comment]
Wow! I had heard that you might be thinking about this. Very cool.

Now, I have a couple of naive questions.

What do you mean by "repos"? What is it that you are pushing?

**Comment by tengfei** [comment]
Hi @seandavi thanks for your feedback : ) 

here is my experiments and thinking, after parsing from Rmarkdown with lift header, there are basically two units need to be pushed somewhere 1) the docker container (if new container is needed for my app) 2) cwl json app

With sevenbridges API client and token, it will be convenient that I can push everything into sevenbridges platform (including CGC) for both container and cwl app for a single user account/token.  But what if I want to push docker container to dockerhub or other place, then I probably need user to provide a single config file that similar to docker login created to manage multiple docker resgistry, then in R, I specify the docker registry I want to push, then specify the cwl json repos I want to push to.  I want to give user broad options in a long run for sure, but first need to prototype with CGC to demonstrate the idea.

**Comment by seandavi** [comment]
I see.  You meant both container and json.  Seems like you might almost want a "handler" capability here--that is, code rather than config.  I can imagine some pretty esoteric authentication/authorization schemes that people might want to use.  You could supply default handlers for CGC, dockerhub, and github (for json, for example).  Just thinking out loud, though.

**Comment by tengfei** [comment]
Thanks, that's very good advice!  At first, I kind of limit my mind to our own service on CGC ; ) I will provide flexible handler capability for customized push or publish.

**Comment by tengfei** [comment]
not the scope of this package anymore, think about factorize cwl component separately.
