### ISSUE TITLE
test with rabix/bunny

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#19]
How we make it better integrated with bunny? Can we run local test from bunny for our CWL Tool or Flow object? This enhancement is going to be easier for developers to test their app with test data (maybe in the IDE container?) need more discussion and brainstorm on this.

**Comment by duxan** [comment]
I played a bit with testing tools from docker image (could be integrated in IDE docker). I have also tried to simplify that testing workflow, so user can call bunny directly from R (with only 2 quick and dirty functions: `set_test_env()` and `test_tool()`) - commit 1bb98c5. I succeed to pass rabix tool defined with the package and inputs to bunny and to get bunny logs, but there are several problems still to resolve (docker requirement as major, and also relative paths to files). 

Another possibility could be to pack bunny binaries with package and run it on host system if Java is installed.

**Comment by tengfei** [comment]
@duxan wow that's fast, I will try it on Monday, thanks a lot! Can I add you as one of the author?

**Comment by duxan** [comment]
I'm not sure if current bunny version I packed in docker image (v0.3.0-alpha) works as expected (docker hint is not evaluated) - I'll check with Janko and Sinisa - but calling some commands from container itself (not docker inside docker) works well. Main concern with this flow is docker cmds invoking from R to host system. It is cumbersome in this initial setup: separate class would be better solution to handle different docker cmds we are using throughout sevenbridges-r use cases or even better - full R package as docker client API - since there isn't one there!

I have also switched this testing issue to separate branch, hope it is ok with you. Just another thing: can you add hook for Dockerfile autobuild for /inst/testenv/Dockerfile (it is also in master branch)?

Will get back to you soon with better docker cmds handling and info about current status of bunny-docker issue.

**Comment by tengfei** [comment]
Thanks again for such a quick implementation! I added you as author as well, I totally agree we need something like docker-py in R : ) this is the pain, when I try to deal with different platforms, for example, run docker from R on my mac with docker machine, a docker API R package will make it easier to do so. So let's do it : )  and when we publish it, let's ask docker to mirror our repos into their official Github account as well maybe.  Also if I have ubuntu docker container running with Rstudio server, can I run local test in that Rstudio (docker in docker) is another problem I have in mind. 

Please feel free to create any branch and merge back at any point. btw, I create link to tengfei/testenv dockerfile it's built already. When the local executor with bunny works, I will make Task object executable locally by calling your function.

**Comment by duxan** [comment]
It seems docker-in-docker could be problematic: I ran to small-to-medium problems like "not enough space in container", pulling images I already have on host, authenticating to images.sbgenomics.com - to more serious ones of not being able to reliable mount volumes from host through layers.

Another cool solution I'm investigating is to map/mount host socket, so when container has docker executable it runs with docker server from host: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ and starts containers from host images (no memory issues, no duplicate pulling) as sibling containers as opposed to child containers. Rabix in python (rabix-legacy) from devel branch works  well - starts docker containers and executes tasks, but I have a problem of "catching" output files (seeing mounted paths).

Bunny is non-responsive atm when it comes to pulling images and running containers.

**Comment by tengfei** [comment]
sorry I missed this reply, yes I remember I am testing host socket mapping last time I work with docker in docker issues, I think it's by far the best solution. 

at fist I have been thinking, is there multiple user issues for the same host mapping, but I think this is too edge now, manager of that instance should be aware of this when they give permission to group members, for example, if a group use the same Rstudio server and run local test,  they should realize host mapping, on the other hand, it's probably also cool in this situation,  so no duplicated pulling and even docker container is shared cross group members.

btw, thank you so much for working on this hard problem : )

**Comment by tengfei** [comment]
not the scope of this package anymore
