### ISSUE TITLE
Build vignettes failed when installing from github

### ISSUE THREAD

**Issue by duxan** [sbg/sevenbridges-r#2]
Hi,

When installing from github:

```
source("http://bioconductor.org/biocLite.R")
useDevel()
biocLite("BiocUpgrade")
library(devtools)
install_github("tengfei/sevenbridges", build_vignettes=TRUE, 
  repos=BiocInstaller::biocinstallRepos(),
  dependencies=TRUE, type = "source")
```

I get an error: 

```
Quitting from lines 155-183 (bioc-workflow.Rmd) 
Error: processing vignette 'bioc-workflow.Rmd' failed with diagnostics:
invalid assignment for reference class field 'token', should be from class "character" or a subclass (was class "NULL")
Execution halted
```

It is a tiny issue - pull request that fixes it is #1

p.s. great work btw.

**Comment by tengfei** [comment]
Hi @duxan thanks a lot for your feedback, actually before I see this issue this afternoon, I fixed some other problem together today and pushed to bioconductor svn. Usually after that, I do a git svn rebase to sync to here. I think I fixed the problem for building vigenettes problems. The release date is in April, hopefully the installation will be easier for R users later (biocLite() will work for both released and devel branch). btw, I mainly use Bioconductor svn for development, github is more like a mirror, but please feel free to submit pull request, I may directly edit in bioc svn.
