### ISSUE TITLE
Possible to take cwl.json and abstract out to sevenbridges R package wrapping?

### ISSUE THREAD

**Issue by davidroberson** [sbg/sevenbridges-r#21]

**Comment by tengfei** [comment]
hey dave, do you mean to import a cwl app json to a R Tool or Flow object defined in sevenbridges package? For example, when you download a json from the platform, and you want to import it into R as an object? I don't have it now but actually on the roadmap, could you please give me a use case for this situation? thanks a lot!

**Comment by tengfei** [comment]
convert_app function convert a tool or worklfow json into a Tool or Workflow object in R now.

**Comment by seandavi** [comment]
Very nice!  I was just thinking about the need for this.

Sean
