### ISSUE TITLE
volumn API support

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#22]
http://docs.sevenbridges.com/docs/creating-a-volume

**Comment by seandavi** [comment]
Hi, Tengfei.  Is this part of the cgc api, do you know?

**Comment by tengfei** [comment]
not sure about cgc yet, but I do mean this one http://docs.sevenbridges.com/docs/creating-a-volume

**Comment by tengfei** [comment]
supported now in github.
