### ISSUE TITLE
export FilesList() to users and make sure single file works in case of file array

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#23]
Public API related validation question 
- when file array specified, should I pass a single file a list of a single file
- when file[not array] specified, can I pass a single file or a list of a single file

need to test and need clear documentation, or make the R API extremely simple so user won't think about it or worry about it at all.

**Comment by seandavi** [comment]
Thanks, Tengfei, for thinking about this. It would be great to have the array[TYPE] and TYPE dealt with relatively transparently.  That said, that will require some work to get right (and a fair number of edge cases, I suspect).

**Comment by tengfei** [comment]
yes, I just checked our API, currently when input need array, user have to pass an array even for single file, in current version of sevenbridges R, they can simply pass list(some files or single file) and it will be converted automatically to a FilesList object inside, but I want to make it easier for R client side, because otherwise user have to always check input node type first before they assign input to a task or a job. I can make it automatically converted, but this need to consider different case 1. app in the cloud need to pull input type details and do the check and conversion 2. local app, easier, can check type on the fly.

**Comment by seandavi** [comment]
Yes, I see the problem. Could you go the route of allowing the user to specify `type_check=TRUE` for task submissions? If you do that, I guess you would need a handler that can find and parse the app description.  The default handler could be one that pulls the description from SBG, but one could specify raw json or a connection to get it from local file or even text, etc. The default could be `type_check=FALSE` which assumes that the user knows what the inputs should be.  I am just thinking out loud.

**Comment by tengfei** [comment]
thanks Sean, this is actually the way I am trying to improve it now ; )

**Comment by seandavi** [comment]
Great.  I wish I could be more constructive, but hopefully hearing from our local users has been helpful.

**Comment by tengfei** [comment]
Honestly speaking, It's been very very helpful with your feedback and help and your colleges' feedback, so I can see what real users think and how they use it in their real work, does it cause any trouble,  this is very important for the package development and improvements, so please keep sending me feedback, bug report, feature request, I really appreciate that!

**Comment by DurgaAdd** [comment]
If I am getting this right, as a user, I would like to have the default type_check=TRUE  and not have to check input node type, for public apps hosted by SBG, esp'ly when using credits to run the tasks!

**Comment by tengfei** [comment]
hi Durga, just in the context of this thread, if users are able to run the tasks and then it fails, theoretically it should not caused by the input type mismatch, because you won't be able to draft/run the task with wrong input type, you will get error message, so this won't cost credits. Like the one we recently debugged, it turns out to be a problem for a missed meta field of pair-end reads files. 

but you are right, for R user, I will make it as simple as possible, that means*\* coercion*\* for edge cases like FilesArray accept single file input, de-array a list of single file for single file input node will happen by default to save user's time.

It's different from generic **type input validation**, We always have type input validation on our server and give you meaningful error message (we have been improving that message system). The 'type_check'  feature discussed here will be R client side checking, which is not relying on server side validation,  happens when you construct a draft job or task in R before you executing it in the cloud or with bunny. It will be a new feature,  not exactly the same for the case above , so I probably need to make a separate ticket for it, the goal is provide validation and coercion where possible.

It's trickier sometimes, for example, users pass 1 to integer input in R, I can convert to 1L, but what if user pass 2.3, I don't want to convert it to 2L automatically,  I cannot assume what happened here.  For this one, I may make global option to non-auto-conversion, only give hints message by default for diagnostics,  user should trust more on server side validation message, otherwise it's even harder to debug when something happens downstream of execution. Just some thoughts.

**Comment by DurgaAdd** [comment]
Much clear now, thanks Tengfei. I think I was puzzled by my draft task which got created but was not run actually. there was no error message on R client, but in the UI I could see the message "Unknown file name". 
I think you got this covered now, thank you for a very prompt and wonderful support!
