### ISSUE TITLE
Improve CWL workflow construction in R

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#24]
Currently t1 %>>% t2 only support simple flow simple matching, but we need flexible extra parameter in Flow function, that allow user to connect by id directly, so they can create non-linear or complex flow from R script easily.

**Comment by tdelhomme** [comment]
Do we have the possibility to pass an input to the workflow which is needed by not the first process? for example I have a workflow which chain platypus and bgzip, and I want an input only pass to bgzip, is this possible?

**Comment by nanxstats** [comment]
We will probably support authoring v1 workflows in a new, separate R package directly, based on SBG's Python implementation [sevenbridges-cwl](https://github.com/sbg/sevenbridges-cwl).

Closing this for now.
