### ISSUE TITLE
CWL draft-3 support

### ISSUE THREAD

**Issue by mr-c** [sbg/sevenbridges-r#26]
This is great! It would be super nice if CWL draft-3 was supported.

**Comment by tengfei** [comment]
hi @mr-c thanks a lot for your feedback, I just got back from conference, after I finished this round of fix, I will start working on CWL-draft3 asap : )

**Comment by tengfei** [comment]
A quick comment here, I am directly working on V1.0 now, will skip draft 3.

**Comment by nanxstats** [comment]
As the current implementation is practically compatible with draft2/3 and v1, we'll keep supporting them and patching this code up as these versions evolve.

We will probably support authoring v1 workflows in a new, separate R package directly, based on SBG's Python implementation [sevenbridges-cwl](https://github.com/sbg/sevenbridges-cwl).

I'm closing this for now.
