### ISSUE TITLE
support for SBG "Test" tab

### ISSUE THREAD

**Issue by davidroberson** [sbg/sevenbridges-r#31]
I test multiple revisions of a tool on CGC/SBG platform.  Every time the revision is pushed the "Test" tab is blanked out and I have to re-input to test the command line expression.

Would be great if I could add the "Test" information via R script.

**Comment by tengfei** [comment]
Interesting, I need to figure out wether it's generic public API problem are the R client's problem. thanks Dave!

**Comment by tengfei** [comment]
I think it's more like a new feature on platform, if the public API doesn't support this feature, R client cannot easily do it. I will file a ticket for this, it's a very good suggestion.

**Comment by duxan** [comment]
I believe that test values are kept in "sbg:job" key of tool.json when viewed on platform (and also accessible through API). If that info is added to tool json in R and then uploaded as new revision - it should preserve the same test values. Haven't tested it though.

**Comment by tengfei** [comment]
Thanks a lot @duxan I think this is the answer, it should work. my bad I forget this, because I did quick test and forget to "save" it before export to json, then wondering why it's not encoded in my cwl .....

@davidroberson could you please try something like this and push it. 

```
rbx <- Tool(id = "runif",
            label = "Random number generator",
            hints = requirements(docker(pull = "tengfei/runif"), 
                                 cpu(1), mem(2000)),
            baseCommand = "runif.R",
            inputs = in.lst, ## or ins.df
            outputs = out.lst, 
            'sbg:job' = list(allocatedResources = list(mem = 9000, 
                                                       cpu = 1), 
                             inputs = list(
                                 min = 1, 
                                 max = 150
                             )))

```

At the same time, I may need to make it easier to allow user pass "job" directly.

**Comment by tengfei** [comment]
Add `keep_test` argument to task_add() so when you push a Tool object with no sbg:job info, you can still use `keep_test = TRUE` to keep previous test info.
