### ISSUE TITLE
Task Download Issue

### ISSUE THREAD

**Issue by nanxstats** [sbg/sevenbridges-r#52]
Investigate the task download issue mentioned in https://github.com/sbg/sevenbridges-r/issues/51

**Comment by ihelbig** [comment]
Even though the task is completed, it does not download. 
![screen shot 2017-02-21 at 9 13 12 pm](https://cloud.githubusercontent.com/assets/25822720/23194196/b8ccb230-f87a-11e6-8636-4b4579af0240.png)

**Comment by ihelbig** [comment]
Just a quick fix: while `tsk$download()` does not work `tsk$file()$download()` works well
![screen shot 2017-02-22 at 1 20 09 am](https://cloud.githubusercontent.com/assets/25822720/23199590/3bfa909c-f89d-11e6-8d97-4452b5f343fc.png)

**Comment by astewart-twist** [comment]
Same problem here but the `tsk$file()$download()` work around doesn't work for me.

**Comment by nanxstats** [comment]
Hi @ihelbig @astewart-twist ,

-- this should be fixed by https://github.com/sbg/sevenbridges-r/commit/45c8ec91bfb79537aa50a582196e5e3f6ed3e05f , could you please try installing the GitHub version and test if it works? Thank you.

In the current implementation, downloading task output files should work as expected; downloading running tasks will not throw errors, and no actual files will be downloaded.

If this works, we will try to release this version to Bioconductor soon, presumably next week.

Thanks again for reporting issues, please feel free to do so if any further issues are encountered when using this package, it will help us a lot on improving the package quality.

-Nan

**Comment by astewart-twist** [comment]
Yup, that one works!  

I was able to get around this btw with `tsk$file()[[1]]$download("downloads/")` for each file.  Not terribly inconvenient to iterate through, but the single method call directly off of `tsk` is very much appreciated.

Thanks!

**Comment by nanxstats** [comment]
@astewart-twist -- terrific! Thanks a lot for the test. Really happy to hear that the patch works.
