### ISSUE TITLE
Formalize Enterprise API (until official release)

### ISSUE THREAD

**Issue by nanxstats** [sbg/sevenbridges-r#57]
Implement the Enterprise API for division/team/member management.

**Comment by SenadI** [comment]
@road2stat  AA feature. Just a reminder. Will suffer from improvements in the future.

**Comment by nanxstats** [comment]
@SenadI -- yes, as is indicated in the title: **(until official release)**.

**Comment by nanxstats** [comment]
Fixed by https://github.com/sbg/sevenbridges-r/releases/tag/v1.13.3.
