### ISSUE TITLE
baseCommand is empty after convert_app()

### ISSUE THREAD

**Issue by tdelhomme** [sbg/sevenbridges-r#59]
When I try to convert a public app to a tool, the base command is lost.

```
> t=convert_app(a$public_app(name = "bgzip"))
Warning message:
In .asTool(obj) :
  Extra fields dropped before conversion: sbg:appVersion sbg:projectName cwlVersion

> t$baseCommand
NULL
```

**Comment by tdelhomme** [comment]
@tengfei 
I have the same problem when trying to convert an app from JSON file following the tutorial [here](https://sbg.github.io/sevenbridges-r/articles/apps.html#import-from-json-file)... 

```
> t1 = system.file("extdata/app", "tool_star.json", package = "sevenbridges")
> # # convert json file into a Tool object
> t1 = convert_app(t1)
> t1$baseCommand
NULL
```

weird!

**Comment by tdelhomme** [comment]
It seems that it happens only when use an array for `baseCommand` in JSON file, if string is used, `baseCommand` is well imported in R.

**Comment by tengfei** [comment]
Thanks @tdelhomme,  it's good catch, I just fix the bug and push it on github with recent two commits. (I also fix warning you got). Please let me know if it still doesn't work

**Comment by nanxstats** [comment]
-great! Thanks @tengfei for the fix. I've just pushed the latest changes to Bioconductor. The new version (release: 1.6.4, devel: 1.7.4) will propagate through Bioc's build system and appear on their website in about 24 hours.
