### ISSUE TITLE
Error while drafting task

### ISSUE THREAD

**Issue by kgaonkar6** [sbg/sevenbridges-r#70]
Hello,

I am generating a batched task as below:
tsk_batch <- pid$task_add(name="XX_index",batch = batch(input = "input_bam_file"),
                    app = "gaonkark/XX_project/bamtools-index-2-4-0", inputs=list(input_bam_file=tumor_normal_pairs$File.Name.Tumor),use_interruptible_instances = TRUE)
 
(This had worked before for another project but seems to error out now) The error I get is as follows:
file name: XXXY
file name: XXXZ
Task drafting ...
Done
Error in envRefSetField(.Object, field, classDef, selfEnv, elements[[field]]) : 
  ‘execution_settings’ is not a field in class “Task”

Can you please let me know how I can fix this issue? I tried to give execution_settings =list(instance_type="c4.8xlarge,2048") but still get the same error.

Thank you,
Krutika

**Comment by kgaonkar6** [comment]
Updating the R package fixed the issue. I was able to run the same command without any errors.

Thanks!

**Comment by kgaonkar6** [comment]
Updating the R package helped fix the issue.

Thanks!

**Comment by nanxstats** [comment]
@kgaonkar6 -no worries, sorry for the inconvenience and glad it works!
