### ISSUE TITLE
Error when trying to create  new draft task

### ISSUE THREAD

**Issue by silpasuthram** [sbg/sevenbridges-r#71]
I am trying to create a new draft task using inputs from a previous task.  See code below:
 p$task_add(
+   name = "TCGA ERV run - rerun failed task",
+   description = "Find ERVs in Cancer",
+   app = ap$id,
+   inputs = list(genome = gen,bam_file = bm,input_file_a =inp)
+ )

But when I run it, I get the following error:

checking inputs ...
check id match
file name: GRCh38_full_analysis_set_plus_decoy_hla.phiX174.Homo_sapiens.GRCh38.84.star-2.6.0c-index-archive.tar
file name: c51f3e01-bc8f-4c37-91cf-35cbd943cd54_gdc_realn_rehead.bam
file name: ERVmap_v2_all_sorted.bed
Task drafting ...
Done
**Error in envRefSetField(.Object, field, classDef, selfEnv, elements[[field]]) : 
  ‘execution_settings’ is not a field in class “Task”**
Can you help?

**Comment by nanxstats** [comment]
Hi @silpasuthram -this is related to some recent improvements in the backend and the API, please update the package to the latest version (1.13.3), and that should resolve the issue.

To install the latest release version from Bioconductor, first make sure Biocondutor is updated to the latest release version (3.8), if not:

```r
BiocManager::install(version = "3.8")
```

This probably will update all the Bioc packages to their latest version in the 3.8 branch. If not, use

```r
BiocManager::install("sevenbridges")
```

to install/update it specifically.
