### ISSUE TITLE
Cannot extend  docker image with packages

### ISSUE THREAD

**Issue by Pantelispanka** [sbg/sevenbridges-r#72]
FROM sevenbridges/sevenbridges-r

RUN R -e "install.packages(c('BiocManager'), repos='http://cran.cc.uoc.gr/mirrors/CRAN/')"

RUN R -e "BiocManager::install(c('GEOquery'), dependencies=T)"
RUN R -e "BiocManager::install(c('limma'), dependencies=T)"
RUN R -e "BiocManager::install(c('annotate'), dependencies=T)"
RUN R -e "BiocManager::install(c('oligo'), dependencies=T)"
RUN R -e "BiocManager::install(c('oligoClasses'), dependencies=T)"
RUN R -e "BiocManager::install(c('crossmeta'), dependencies=T)"
RUN R -e "BiocManager::install(c('genefilter'), dependencies=T)"

Some packages as  oligo can't be installed is there something wrong? 

Thanks a lot!

**Comment by nanxstats** [comment]
-ok, the Docker image was built on `rocker/tidyverse`, so I don't see a major issue extending it. Other than that, we probably need more information than "can't be installed" to solve the issue.
