### ISSUE TITLE
task run error

### ISSUE THREAD

**Issue by kgaonkar6** [sbg/sevenbridges-r#77]
Hello,

When I try to run the command from Rstudio using tsk$run() it errors out as 

```
Error: HTTP Status 400: Invalid JSON input
Called from: status_check(req)
Browse[1]> Q
```

but it successfully runs through clicking "Run" button through GUI. 

Please let me know how I can fix this issue (I'm using 1.17.1 sevenbridges version)

Thanks!

**Comment by nanxstats** [comment]
Hey @kgaonkar6 please try version 1.18.1 from Bioconductor (release branch), or, equivalently, 1.19.1 from the devel branch / GitHub. If the issue persists, we probably need to take a look at the workflow and check if there is an input format problem.

**Comment by kgaonkar6** [comment]
I'm closing this issue. 1.19.1 from Github fixed it, thanks!
