### ISSUE TITLE
Docker image build issue

### ISSUE THREAD

**Issue by Shanshan-Qu** [sbg/sevenbridges-r#79]
Hi,

We want to build an image to be used in AWS Fargate service. We tried to pull from docker, but the version is old like 2 years ago.

https://hub.docker.com/r/sevenbridges/sevenbridges-r/tags?page=1&ordering=last_updated

Then tried to follow the steps mentioned in the Tutorials part:

https://sbg.github.io/sevenbridges-r/articles/rstudio.html

Seems the Dockerfile can't work well and I get the following error:

09:44:25  Ign:1 https://download.docker.com/linux/debian focal InRelease
09:44:25  Err:2 https://download.docker.com/linux/debian focal Release
09:44:25    404  Not Found [IP: 13.224.179.55 443]
09:44:25  Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
09:44:25  Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
09:44:25  Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
09:44:26  Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
09:44:26  Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [778 kB]
09:44:28  Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [687 kB]
09:44:28  Reading package lists...
09:44:28  [91mE: The repository 'https://download.docker.com/linux/debian focal Release' does not have a Release file.
09:44:28  [0mThe command '/bin/sh -c apt-get update     && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common     && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -     && apt-key fingerprint 0EBFCD88     && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"     && apt-get update -y     && apt-get install -y docker-ce' returned a non-zero code: 100

Can you show me how can I build the latest image to be used in AWS Fargate?

Thanks
shanshan

**Comment by skoc** [comment]
Hi @Shanshan-Qu 

good question, thank you - while we are updating the image on the **hub.docker** and the **Dockerfile**, you can use the **Dockerfile** that you already used with a quick fix:

Please change this section in the **Dockerfile** (/inst/docker/sevenbridges):

```
## Install Docker

RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
    && apt-key fingerprint 0EBFCD88 \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    && apt-get update -y \
    && apt-get install -y docker-ce
```

with this one:

```
## Install Docker

RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
    && apt-key fingerprint 0EBFCD88 \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" \
    && apt-get update -y \
    && apt-get install -y docker-ce
```
Please let me know how it goes!

**Comment by Shanshan-Qu** [comment]
> Hi @Shanshan-Qu
> 
> good question, thank you - while we are updating the image on the **hub.docker** and the **Dockerfile**, you can use the **Dockerfile** that you already used with a quick fix:
> 
> Please change this section in the **Dockerfile** (/inst/docker/sevenbridges):
> 
> ```
> ## Install Docker
> 
> RUN apt-get update \
>     && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common \
>     && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
>     && apt-key fingerprint 0EBFCD88 \
>     && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
>     && apt-get update -y \
>     && apt-get install -y docker-ce
> ```
> 
> with this one:
> 
> ```
> ## Install Docker
> 
> RUN apt-get update \
>     && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common \
>     && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
>     && apt-key fingerprint 0EBFCD88 \
>     && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" \
>     && apt-get update -y \
>     && apt-get install -y docker-ce
> ```
> 
> Please let me know how it goes!

Hi Skoc,

Thanks for your reply. It passed the Install Docker part, but failed again with the following error:

09:24:24  Removing intermediate container f934e5ec1d92
09:24:24   ---> 74bd1fe5ca82
09:24:24  Step 7/20 : ADD src/runif.R /usr/local/bin/
09:24:24  ADD failed: stat /var/lib/docker/tmp/docker-builder574908531/src/runif.R: no such file or directory

Can you help check again?

Thanks
shanshan

**Comment by skoc** [comment]
Hey @Shanshan-Qu 

It looks `src/ ` folder to read necessary scripts which is in `sevenbridges-r/inst/docker/sevenbridges`

Try this:

```
cd sevenbridges-r/inst/docker/sevenbridges
docker build -t sevenbridges/sevenbridges-r .
```

OR

`docker build -t sevenbridges/sevenbridges-r sevenbridges-r/sevenbridges-r/inst/docker/sevenbridges/.
`

**Comment by Shanshan-Qu** [comment]
> Hey @Shanshan-Qu
> 
> It looks `src/ ` folder to read necessary scripts which is in `sevenbridges-r/inst/docker/sevenbridges`
> 
> Try this:
> 
> ```
> cd sevenbridges-r/inst/docker/sevenbridges
> docker build -t sevenbridges/sevenbridges-r .
> ```
> 
> OR
> 
> `docker build -t sevenbridges/sevenbridges-r sevenbridges-r/sevenbridges-r/inst/docker/sevenbridges/. `

Hi Soner,

yes, I get what you mean, but it will point to the Dockerfile below which I am using. 

https://github.com/sbg/sevenbridges-r/blob/master/inst/docker/sevenbridges/Dockerfile

Below is the one I am currently using with the change you mentioned for the docker install part. 

```
FROM rocker/tidyverse

LABEL maintainer="soner.koc@sevenbridges.com"

## Install common dependencies
RUN apt-get update && apt-get install -y  \
    sudo \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    curl \
    libcairo2-dev \
    libxt-dev \
    unp \
    emacs \
    supervisor \
    libfuse-dev \
    gnupg
#   aufs-tools \
#   cgroupfs-mount

# RUN wget --no-verbose http://ftp.us.debian.org/debian/pool/main/l/lvm2/libdevmapper1.02.1_1.02.136-1_amd64.deb && \
#    dpkg -i libdevmapper1.02.1_1.02.136-1_amd64.deb && \
#    rm -f libdevmapper1.02.1_1.02.136-1_amd64.deb

# RUN wget --no-verbose http://ftp.us.debian.org/debian/pool/main/libt/libtool/libltdl7_2.4.6-2_amd64.deb && \
#    dpkg -i libltdl7_2.4.6-2_amd64.deb && \
#    rm -f libltdl7_2.4.6-2_amd64.deb

## Install Docker

## Install Docker

RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - \
    && apt-key fingerprint 0EBFCD88 \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" \
    && apt-get update -y \
    && apt-get install -y docker-ce

##################
# sevenbridges-r #
##################

# Install from GitHub instead of Bioconductor for the latest version
RUN Rscript -e "install.packages('BiocManager');\
    devtools::install_github('sbg/sevenbridges-r', repos = BiocManager::repositories(), build_vignettes = FALSE, dependencies = TRUE)"

#####################
# Seven Bridges SDK #
#####################

## Install SBG Rabix
RUN wget https://github.com/rabix/bunny/releases/download/v1.0.5-1/rabix-1.0.5.tar.gz \
    && tar -zvxf rabix-1.0.5.tar.gz \
    && ln -s  /rabix-cli-1.0.5/rabix /usr/local/bin/rabix

## Install SBG Command line uploader
# RUN wget https://igor.sbgenomics.com/sbg-uploader/sbg-uploader.tgz \
#     && tar zxvf sbg-uploader.tgz -C / \
#    && ln -s  /sbg-uploader/bin/sbg-uploader.sh /usr/local/bin/sbg-uploader.sh

## Install CGC Command line uploader
# RUN wget https://cgc.sbgenomics.com/cgc-uploader/cgc-uploader.tgz \
#    && tar zxvf cgc-uploader.tgz -C / \
#    && ln -s  /cgc-uploader/bin/cgc-uploader.sh /usr/local/bin/cgc-uploader.sh

## Copy command line interface and report templates needed
ADD src/runif.R /usr/local/bin/
RUN mkdir /report/
ADD report/report.Rmd /report/

## Install liftr and packrat
RUN Rscript -e "install.packages(c('liftr', 'packrat'), repos = 'https://cloud.r-project.org/')"

## (because --deps TRUE can fail when packages are added/removed from CRAN)
RUN rm -rf /var/lib/apt/lists/ \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

################
# Shiny Server #
################

## Thanks: rocker-org/shiny

## Download and install Shiny Server
RUN wget --no-verbose https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/VERSION -O "version.txt" && \
    VERSION=$(cat version.txt)  && \
    wget --no-verbose "https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/shiny-server-$VERSION-amd64.deb" -O shiny-server-latest.deb && \
    gdebi -n shiny-server-latest.deb && \
    rm -f version.txt shiny-server-latest.deb

RUN Rscript -e "install.packages(c('shiny', 'rmarkdown', 'rsconnect'), repos = 'https://cloud.r-project.org/')"

RUN cp -R /usr/local/lib/R/site-library/shiny/examples/* /srv/shiny-server/

RUN mkdir /home/rstudio/ShinyApps/

RUN cp -R /usr/local/lib/R/site-library/shiny/examples/* /home/rstudio/ShinyApps/

EXPOSE 3838 8787

# COPY src/shiny-server.sh /usr/bin/shiny-server.sh
# RUN wget --no-verbos https://raw.githubusercontent.com/sbg/sevenbridges-r/master/inst/docker/sevenbridges/src/shiny-server.conf -P /etc/shiny-server/
# RUN wget --no-verbos https://raw.githubusercontent.com/sbg/sevenbridges-r/master/inst/docker/sevenbridges/src/supervisord.conf    -P /etc/shiny-server/
COPY src/shiny-server.conf  /etc/shiny-server/shiny-server.conf
COPY src/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

## set directory to `~/ShinyApps`
# RUN yes | /opt/shiny-server/bin/deploy-example user-dirs
# RUN cp -R /usr/local/lib/R/site-library/shiny/examples/* ~/ShinyApps/

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
# CMD ["/init;/usr/bin/shiny-server.sh"]
# CMD ["sh", "-c", "/usr/bin/shiny-server.sh;/init"]
```

Thanks
shanshan

**Comment by skoc** [comment]
Hey @Shanshan-Qu 

you can overwrite the `/master/inst/docker/sevenbridges/Dockerfile` with the edited one.
Could you also share all your steps that you followed  and to know your system specs will be helpful too?

**Comment by Shanshan-Qu** [comment]
Thanks for your help, I have built the image successfully.
