### ISSUE TITLE
Add spin example for single R script 

### ISSUE THREAD

**Issue by tengfei** [sbg/sevenbridges-r#8]
recommended by Dusan, very good point, also see examples from Dave as well, need good example for spin.

**Comment by davidroberson** [comment]
I have actually moved away from using spin lately.  I have found that .Rmd is formatted much better in RStudio and allows publishing directly to shinyapps.io with a mouse click.  For every project I have 1 long .Rmd that can create 1 or more .R files.  These .R files use doctopt to get the commands lines args and feed back to the .Rmd.  The last command in the .R is render("project.Rmd") with the command line args present in the environment already.

I suppose this same strategy could be done with 1 .R file but for me I prefer the formatting of the .Rmd in RStudio.  The .R file is more concise though and could be used to spin itself.

**Comment by tengfei** [comment]
hi dave, this sounds great, could you please send me your example Rmd  privately to me, so I could get a rough idea for your approach? For the spin example, I now simply want to add a short example that people add .R via fileDef and use base command to spin that into a pdf/html report.

**Comment by davidroberson** [comment]
Sounds great.  I will send you an Rmd later this week.  It will have a description of how to wrap star genome generate and star aligner using the sevenbridges package.

**Comment by tengfei** [comment]
Thanks Dave!
